name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  pipelineRepo:
    required: false
    description: |
      repo with Flux manifests
      defaults to current repo
  pipelinePath:
    required: true
    description: path to Flux manifests
    default: './.kustomization/preview'
  secretName:
    required: true
    description: |
      name of github secret in cluster to reference for deploys
      should have access to pipelineRepo
    default: github-token
  deployTag:
    required: true
    description: image tag to deploy
    default: latest
  namespace:
    required: true
    description: kubernetes namespace to target
  serviceName:
    required: false
    description: override service name, defaults to name of repo
  skipCheck:
    required: true
    description: skips checking PR event and just deploy
    default: "false"
runs:
  using: 'node12'
  main: 'dist/index.js'
