name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  kustomizePath: 
    required: true
    description: path to kustomization in git repo
  repoSecret:
    required: true
    description: name of github secret in cluster
runs:
  using: 'node12'
  main: 'dist/index.js'
