name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  kustomizePath: 
    required: true
    description: path to kustomization in git repo
  repoSecret:
    required: true
    description: name of github secret in cluster
  deployImage:
    required: true
    description: deploy image
  namespace:
    required: true
    description: deploy namespace
  forceDeploy:
    required: false
    description: if should deploy even during a sync action
runs:
  using: 'node12'
  main: 'dist/index.js'
