apiVersion: v1
kind: Config
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: http://localhost:8080
  name: mock-cluster
contexts:
- context:
    cluster: mock-cluster
  name: mock
current-context: mock
